# Generated by Django 4.0.3 on 2022-08-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_id', models.IntegerField(default=0, verbose_name='Номер строки № ')),
                ('order_id', models.IntegerField(default=0, verbose_name='Заказ №')),
                ('order_eu', models.IntegerField(default=0, verbose_name='Стоимость, $')),
                ('order_ru', models.IntegerField(default=0, verbose_name='Стоимость, ₽')),
                ('date', models.CharField(default=0, max_length=10, verbose_name='Срок поставки')),
            ],
            options={
                'verbose_name': 'новую строку',
                'verbose_name_plural': '1) Таблица',
            },
        ),
    ]
