# Generated by Django 4.0.3 on 2022-08-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_tables_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.CharField(default='Вкл', max_length=4, verbose_name='Вкл/Выкл')),
                ('time', models.IntegerField(default=10, verbose_name='Обнавлять данные каждые(мин)')),
            ],
            options={
                'verbose_name': 'новую строку',
                'verbose_name_plural': '2) Настройки авто-обнавления',
            },
        ),
    ]
