# Generated by Django 4.0.3 on 2022-08-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_autoupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutoUpdate',
        ),
    ]
