# Generated by Django 4.2 on 2023-04-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_delete_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AddField(
            model_name='category',
            name='id_category',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='id'),
            preserve_default=False,
        ),
    ]
