# Generated by Django 4.2 on 2023-04-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_category_id_category_id_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id_category',
        ),
        migrations.AddField(
            model_name='category',
            name='id',
            field=models.AutoField(default=12, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
