# Generated by Django 4.2 on 2023-04-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu',
            field=models.ManyToManyField(blank=True, related_name='related_list_of_purchased_games', to='main.category', verbose_name='Список категорий в данном меню'),
        ),
    ]
