# Generated by Django 4.2 on 2023-04-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_menu_menu_menu_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Новое меню', 'verbose_name_plural': '2) Меню'},
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='menu',
            new_name='related_list_of_purchased_games',
        ),
    ]
