# Generated by Django 4.2 on 2023-04-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_menu_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='related_list_of_purchased_games',
        ),
        migrations.AddField(
            model_name='menu',
            name='included_categories',
            field=models.ManyToManyField(blank=True, related_name='included_categories', to='main.category', verbose_name='Список категорий в данном меню'),
        ),
    ]
