# Generated by Django 4.2 on 2023-04-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_menu_activate_this_menu_on_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': '1) Страница',
            },
        ),
    ]
