# Generated by Django 4.2 on 2023-04-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='included_menu',
            field=models.ManyToManyField(blank=True, related_name='included_menu', to='main.menu', verbose_name='Какие меню добавить на страницу'),
        ),
        migrations.AddField(
            model_name='page',
            name='link_page',
            field=models.IntegerField(blank=True, default=2, verbose_name='Ввидите номер страницы к которой добавить меню'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
